# -*- encoding: utf-8 -*-

"""
Declarative SQL Alchemy ORM Base and Shared Column Mixins
---------------------------------------------------------

Defines the single declarative :class:`ORMBase` shared by every schema in the
database, plus a :class:`TimestampMixin` for DB-managed audit columns. A
deterministic constraint naming convention is attached to the metadata so that
Alembic emits stable, human-readable constraint names across autogenerated
migration events.
"""

import datetime as dt

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class ORMBase(DeclarativeBase):
    """
    A project-wide SQL Alchemy ORM declarative base class; all the models will
    inherit so that they share a single :class:`~sqlalchemy.MetaData` instance -
    a prerequisite for cross-schema foreign keys and a single Alembic migration tree.
    """

    metadata = MetaData(naming_convention = {
        "pk": "pk_%(table_name)s", "uq": "uq_%(table_name)s_%(column_0_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s", "ix": "ix_%(column_0_label)s"
    })


class TimestampMixin:
    """
    Mixin adding database-managed ``created_at`` / ``updated_at`` columns, so
    that all the data are stored in UTC format for cross-table referencing, i.e.,
    the timestamps reflect local write activity rather than an upstream source.
    """

    created_at : Mapped[dt.datetime] = mapped_column(
        DateTime(timezone = True), nullable = False,
        server_default = func.now()
    )

    updated_at : Mapped[dt.datetime] = mapped_column(
        DateTime(timezone = True), nullable = True,
        server_default = func.now(), onupdate = func.now()
    )
